---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: prod
spec:
  type: NodePort
  selector:
    app: mysql-container
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-container
  namespace: prod
  labels:
    app: mysql-container
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql-container
  template:
    metadata:
      labels:
        app: mysql-container
    spec:
      containers:
      - name: mysql-container
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: test_root
        ports:
        - containerPort: 3306